name: Build

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 
  
jobs:
  sync-fork:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.time.outputs.timestamp }}
    permissions:
      contents: write
      
    steps:
      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          token: ${{ secrets.MY_SYNC_PAT }}
        
      - name: Sync Fork with Upstream
        env:
          GH_TOKEN: ${{ secrets.MY_SYNC_PAT }}
        run: |
          gh repo sync ${{ github.repository }} -b ${{ github.ref_name }}

      - name: get current time for build date
        id: time
        run: |
          echo "timestamp=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_OUTPUT

  build-debug:
    name: Assemble Debug APK
    runs-on: ubuntu-latest
    needs: sync-fork
    permissions:
      contents: write

    steps:
      - name: echo
        run: echo "${{ needs.sync-fork.outputs.timestamp }}"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_SYNC_PAT }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/*.gradle', 'gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Assemble debug APK
        run: ./gradlew assembleDebug
          
      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v3.0.0
        with:
          token: ${{ secrets.MY_SYNC_PAT }}
          tag_name: nethunter-${{ needs.sync-fork.outputs.timestamp }}
          name: Nethunter app ${{ needs.sync-fork.outputs.timestamp }}
          files: |
            build/outputs/apk/debug/*.apk

  build-release:
    name: Assemble Release APK
    runs-on: ubuntu-latest
    needs: sync-fork
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_SYNC_PAT }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/*.gradle', 'gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Assemble release APK
        run: ./gradlew assembleRelease

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v3.0.0
        with:
          token: ${{ secrets.MY_SYNC_PAT }}
          tag_name: nethunter-${{ needs.sync-fork.outputs.timestamp }}
          files: |
            build/outputs/apk/release/*.apk
