name: Build

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

permissions:
  contents: write 
  
jobs:
  sync-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          
      - name: Hide Sensitive Inputs
        uses: levibostian/action-hide-sensitive-inputs@v1
        
      - name: Sync Fork with Upstream
        # The gh CLI uses this built-in variable automatically
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        run: |
          gh repo sync ${{ github.repository }} -b ${{ github.ref_name }}

  build-debug:
    name: Assemble Debug APK
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/*.gradle', 'gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Assemble debug APK
        run: ./gradlew assembleDebug
          
      - name: get current time for build date
        id: time
        run: |
          echo "timestamp=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_OUTPUT
          
      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v3.0.0
        with:
          body_path: changelog.txt
          tag_name: nethunter-${{ steps.time.outputs.timestamp }}
          name: Nethunter app ${{ steps.time.outputs.timestamp }}
          files: |
            build/outputs/apk/debug/*.apk

  build-release:
    name: Assemble Release APK
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/*.gradle', 'gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Assemble release APK
        run: ./gradlew assembleRelease

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v3.0.0
        with:
          body_path: changelog.txt
          tag_name: nethunter-${{ steps.time.outputs.timestamp }}
          name: Nethunter app ${{ steps.time.outputs.timestamp }}
          files: |
            build/outputs/apk/release/*.apk
